# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [11]:
import sys
print(sys.executable)

c:\Users\rkham\AppData\Local\Programs\Python\Python311\python.exe


In [12]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [14]:
### [your code here]
print(np.__version__)
np.show_config()


2.4.6
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35226",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35226",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.188.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-6ukx7exl/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [15]:
### [your code here]
a = np.random.rand(2, 3, 5)





### 4. Print a.


In [16]:
### [your code here]
print(a)


[[[0.0348237  0.40650762 0.3337198  0.43271783 0.41498445]
  [0.9744322  0.60969795 0.2308936  0.74583138 0.5682567 ]
  [0.00944646 0.35535353 0.75594157 0.44569972 0.38096689]]

 [[0.36568583 0.86593742 0.01243501 0.39966692 0.98431681]
  [0.19186174 0.5847189  0.68587848 0.11086815 0.38036398]
  [0.0839309  0.8667379  0.73831782 0.79815179 0.18531893]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [17]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [18]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [19]:
### [your code here]
print(a.size==b.size)


True



### 8. Are you able to add a and b? Why or why not?


In [20]:
### [your code here]
#c = a + b

#operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [21]:
### [your code here]
c = b.reshape(a.shape)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [22]:
### [your code here]
d = a +c
print(d)

#it works because they have the same shape now


[[[1.0348237  1.40650762 1.3337198  1.43271783 1.41498445]
  [1.9744322  1.60969795 1.2308936  1.74583138 1.5682567 ]
  [1.00944646 1.35535353 1.75594157 1.44569972 1.38096689]]

 [[1.36568583 1.86593742 1.01243501 1.39966692 1.98431681]
  [1.19186174 1.5847189  1.68587848 1.11086815 1.38036398]
  [1.0839309  1.8667379  1.73831782 1.79815179 1.18531893]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [23]:
### [your code here]
print("a:",a)
### [your code here]
print("d:",d)

# values of array d are bigger by 1 due to multiplication compared to a

a: [[[0.0348237  0.40650762 0.3337198  0.43271783 0.41498445]
  [0.9744322  0.60969795 0.2308936  0.74583138 0.5682567 ]
  [0.00944646 0.35535353 0.75594157 0.44569972 0.38096689]]

 [[0.36568583 0.86593742 0.01243501 0.39966692 0.98431681]
  [0.19186174 0.5847189  0.68587848 0.11086815 0.38036398]
  [0.0839309  0.8667379  0.73831782 0.79815179 0.18531893]]]
d: [[[1.0348237  1.40650762 1.3337198  1.43271783 1.41498445]
  [1.9744322  1.60969795 1.2308936  1.74583138 1.5682567 ]
  [1.00944646 1.35535353 1.75594157 1.44569972 1.38096689]]

 [[1.36568583 1.86593742 1.01243501 1.39966692 1.98431681]
  [1.19186174 1.5847189  1.68587848 1.11086815 1.38036398]
  [1.0839309  1.8667379  1.73831782 1.79815179 1.18531893]]]



### 12. Multiply a and c. Assign the result to e.


In [24]:
### [your code here]
e = a + c




### 13. Does e equal to a? Why or why not?


In [25]:
### [your code here]
e == a

#because they have different values 



array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [26]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [35]:
### [your code here]
f = np.empty((2,3,5))
print(f)


[[[ 1.0348237   1.40650762  1.3337198   1.43271783  1.41498445]
  [75.         75.          1.2308936  75.         75.        ]
  [ 1.00944646  1.35535353 75.          1.44569972  1.38096689]]

 [[ 1.36568583 75.          1.01243501  1.39966692  1.98431681]
  [ 1.19186174 75.         75.          1.11086815  1.38036398]
  [ 1.0839309  75.         75.         75.          1.18531893]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [38]:
for i,j,k in np.ndindex(d.shape): 
    if (d[i, j, k] > d_min) and (d[i, j, k] < d_mean): f[i, j, k] = 25 
    if (d[i, j, k] > d_mean) and (d[i, j, k] < d_max): f[i, j, k] = 75 
    if d[i, j, k] == d_mean: f[i, j, k] = 50 
    if d[i, j, k] == d_min: f[i, j, k] = 0 
    if d[i, j, k] == d_max: f[i, j, k] = 100






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [39]:
### [your code here]
print("d:", d)
print("f:", f)


d: [[[1.0348237  1.40650762 1.3337198  1.43271783 1.41498445]
  [1.9744322  1.60969795 1.2308936  1.74583138 1.5682567 ]
  [1.00944646 1.35535353 1.75594157 1.44569972 1.38096689]]

 [[1.36568583 1.86593742 1.01243501 1.39966692 1.98431681]
  [1.19186174 1.5847189  1.68587848 1.11086815 1.38036398]
  [1.0839309  1.8667379  1.73831782 1.79815179 1.18531893]]]
f: [[[ 25.  25.  25.  25.  25.]
  [ 75.  75.  25.  75.  75.]
  [  0.  25.  75.  25.  25.]]

 [[ 25.  75.  25.  25. 100.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  75.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]